version: "3"

networks: 
  stuix:
    driver: macvlan
    driver_opts:
      parent: eth1
    enable_ipv6: true
    ipam:
      config:
      - subnet: 103.158.187.0/24
        gateway: 103.158.187.254
      - subnet: 2a0f:5707:ffe3::/64
        gateway: 2a0f:5707:ffe3::ffff
  ldix:
    driver: macvlan
    driver_opts:
      parent: eth2
    enable_ipv6: true
    ipam:
      config:
      - subnet: 149.112.26.0/24
        gateway: 149.112.26.254
      - subnet: 2a0f:607:1070::/64
        gateway: 2a0f:607:1070::ffff
  cloudclt:
    driver: macvlan
    driver_opts:
      parent: eth3
    enable_ipv6: true
    ipam:
      config:
      - subnet: 187.187.187.0/24
        gateway: 187.187.187.253
      - subnet: 2def:abcd::/64
        gateway: 2def:abcd::ffff
  stutooc:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
      - subnet: 10.187.0.0/29
        gateway: 10.187.0.6
      - subnet: 2fff:ffff::/125
        gateway: 2fff:ffff::6
  ldtooc:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
      - subnet: 10.187.0.8/30
        gateway: 10.187.0.14
      - subnet: 2fff:ffff::4/126
        gateway: 2fff:ffff::e

services:
  stuixrs:
    cap_add:
    - CAP_NET_RAW
    - NET_ADMIN
    - SYS_ADMIN
    privileged: false
    container_name: stuixrs
    build:
      dockerfile: ./stuixrs/Dockerfile
    volumes:
    - ./stuixrs/frr:/etc/frr:ro
    - ./stuixrs:/setup:ro
    command: "/bin/bash /setup/start.sh"
    networks:
      stuix:
        ipv4_address: 103.158.187.1
        ipv6_address: 2a0f:5707:ffe3::1
  as48024:
    cap_add:
    - CAP_NET_RAW
    - NET_ADMIN
    - SYS_ADMIN
    privileged: false
    container_name: as48024
    build:
      dockerfile: ./as48024/Dockerfile
    volumes:
    - ./as48024/frr:/etc/frr:ro
    - ./as48024:/setup:ro
    command: "/bin/bash /setup/start.sh"
    networks:
      stuix:
        ipv4_address: 103.158.187.92
        ipv6_address: 2a0f:5707:ffe3::92
      stutooc:
        ipv4_address: 10.187.0.1
        ipv6_address: 2fff:ffff::1
  cloudflare:
    cap_add:
    - CAP_NET_RAW
    - NET_ADMIN
    - SYS_ADMIN
    privileged: false
    container_name: cloudflare
    build:
      dockerfile: ./cloudflare/Dockerfile
    volumes:
    - ./cloudflare/frr:/etc/frr:ro
    - ./cloudflare:/setup:ro
    command: "/bin/bash /setup/start.sh"
    networks:
      stuix:
        ipv4_address: 103.158.187.34
        ipv6_address: 2a0f:5707:ffe3::34
