version: "3"

networks: 
  10-stuix:
    driver: macvlan
    driver_opts:
      parent: eth1
    enable_ipv6: true
    ipam:
      config:
      - subnet: 103.158.187.0/24
        gateway: 103.158.187.254
      - subnet: 2a0f:5707:ffe3::/64
        gateway: 2a0f:5707:ffe3::ffff
  20-ldix:
    driver: macvlan
    driver_opts:
      parent: eth2
    enable_ipv6: true
    ipam:
      config:
      - subnet: 149.112.26.0/24
        gateway: 149.112.26.254
      - subnet: 2a0f:607:1070::/64
        gateway: 2a0f:607:1070::ffff
  30-cloudclt:
    driver: macvlan
    driver_opts:
      parent: eth5
    enable_ipv6: true
    ipam:
      config:
      - subnet: 187.187.187.0/24
        gateway: 187.187.187.253
      - subnet: 2def:abcd::/64
        gateway: 2def:abcd::ffff
  15-stutooc:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
      - subnet: 10.187.0.0/29
        gateway: 10.187.0.6
      - subnet: 2fff:ffff::/125
        gateway: 2fff:ffff::6
  25-ldtooc:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
      - subnet: 10.187.0.8/29
        gateway: 10.187.0.14
      - subnet: 2fff:ffff::8/125
        gateway: 2fff:ffff::e
  40-cloudflaredns:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
      - subnet: 1.1.1.0/24
        gateway: 1.1.1.253
      - subnet: 2606:4700:4700::/64
        gateway: 2606:4700:4700::ffff
  45-googledns:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
      - subnet: 8.8.8.0/24
        gateway: 8.8.8.253
      - subnet: 2001:4860:4860::/64
        gateway: 2001:4860:4860::ffff
  50-wscorg:
    driver: macvlan
    driver_opts:
      parent: eth3
    enable_ipv6: true
    ipam:
      config:
      - subnet: 103.69.91.232/29
        gateway: 103.69.91.238
      - subnet: 2407:9240:310f:ffff::ffe8/125
        gateway: 2407:9240:310f:ffff::ffee
  55-wscorgclt:
    driver: macvlan
    driver_opts:
      parent: eth4
    enable_ipv6: true
    ipam:
      config:
      - subnet: 139.39.39.0/24
        gateway: 139.39.39.253
      - subnet: 2390:3939:3939::/64
        gateway: 2390:3939:3939::ffff

services:
  stuixrs:
    cap_add:
    - CAP_NET_RAW
    - NET_ADMIN
    - SYS_ADMIN
    privileged: false
    container_name: stuixrs
    build:
      context: ./stuixrs
      dockerfile: Dockerfile
    volumes:
    - ./stuixrs/frr:/etc/frr:ro
    - ./stuixrs:/setup:ro
    sysctls:
    - net.ipv4.ip_forward=1
    - net.ipv6.conf.default.forwarding=1
    - net.ipv6.conf.all.forwarding=1
    - net.ipv6.conf.all.proxy_ndp=1
    - net.ipv6.conf.all.accept_ra=2
    command: "/bin/bash /setup/start.sh"
    networks:
      10-stuix:
        ipv4_address: 103.158.187.1
        ipv6_address: 2a0f:5707:ffe3::1
  as48024:
    cap_add:
    - CAP_NET_RAW
    - NET_ADMIN
    - SYS_ADMIN
    privileged: false
    container_name: as48024
    build:
      context: ./as48024
      dockerfile: Dockerfile
    volumes:
    - ./as48024/frr:/etc/frr:ro
    - ./as48024:/setup:ro
    sysctls:
    - net.ipv4.ip_forward=1
    - net.ipv6.conf.default.forwarding=1
    - net.ipv6.conf.all.forwarding=1
    - net.ipv6.conf.all.proxy_ndp=1
    - net.ipv6.conf.all.accept_ra=2
    command: "/bin/bash /setup/start.sh"
    networks:
      10-stuix:
        ipv4_address: 103.158.187.92
        ipv6_address: 2a0f:5707:ffe3::92
      15-stutooc:
        ipv4_address: 10.187.0.1
        ipv6_address: 2fff:ffff::1
  cloudflare:
    cap_add:
    - CAP_NET_RAW
    - NET_ADMIN
    - SYS_ADMIN
    privileged: false
    container_name: cloudflare
    build:
      context: ./cloudflare
      dockerfile: Dockerfile
    volumes:
    - ./cloudflare/frr:/etc/frr:ro
    - ./cloudflare:/setup:ro
    sysctls:
    - net.ipv4.ip_forward=1
    - net.ipv6.conf.default.forwarding=1
    - net.ipv6.conf.all.forwarding=1
    - net.ipv6.conf.all.proxy_ndp=1
    - net.ipv6.conf.all.accept_ra=2
    command: "/bin/bash /setup/start.sh"
    networks:
      10-stuix:
        ipv4_address: 103.158.187.34
        ipv6_address: 2a0f:5707:ffe3::34
      40-cloudflaredns:
        ipv4_address: 1.1.1.254
        ipv6_address: 2606:4700:4700::1
  cloudflaredns:
    cap_add:
    - CAP_NET_RAW
    - NET_ADMIN
    - SYS_ADMIN
    privileged: false
    container_name: cloudflaredns
    dns: 
    - 1.1.1.1
    - 2606:4700:4700::1111
    #- 198.41.0.4
    build:
      context: ./cloudflaredns
      dockerfile: Dockerfile
    volumes:
    - ./cloudflaredns:/setup:ro
    - ./cloudflaredns/bind/config:/etc/bind:rw
    - ./cloudflaredns/bind/zone:/var/cache/bind:rw
    command: "/bin/bash /setup/start.sh 1.1.1.254 2606:4700:4700::1"
    networks:
      40-cloudflaredns:
        ipv4_address: 1.1.1.1
        ipv6_address: 2606:4700:4700::1111
  ldrs:
    cap_add:
    - CAP_NET_RAW
    - NET_ADMIN
    - SYS_ADMIN
    privileged: false
    container_name: ldrs
    build:
      context: ./ldrs
      dockerfile: Dockerfile
    volumes:
    - ./ldrs/frr:/etc/frr:ro
    - ./ldrs:/setup:ro
    sysctls:
    - net.ipv4.ip_forward=1
    - net.ipv6.conf.default.forwarding=1
    - net.ipv6.conf.all.forwarding=1
    - net.ipv6.conf.all.proxy_ndp=1
    - net.ipv6.conf.all.accept_ra=2
    command: "/bin/bash /setup/start.sh"
    networks:
      20-ldix:
        ipv4_address: 149.112.26.253
        ipv6_address: 2a0f:607:1070::253
  as7720:
    cap_add:
    - CAP_NET_RAW
    - NET_ADMIN
    - SYS_ADMIN
    privileged: false
    container_name: as7720
    build:
      context: ./as7720
      dockerfile: Dockerfile
    volumes:
    - ./as7720/frr:/etc/frr:ro
    - ./as7720:/setup:ro
    sysctls:
    - net.ipv4.ip_forward=1
    - net.ipv6.conf.default.forwarding=1
    - net.ipv6.conf.all.forwarding=1
    - net.ipv6.conf.all.proxy_ndp=1
    - net.ipv6.conf.all.accept_ra=2
    command: "/bin/bash /setup/start.sh"
    networks:
      20-ldix:
        ipv4_address: 149.112.26.18
        ipv6_address: 2a0f:607:1070::18
      25-ldtooc:
        ipv4_address: 10.187.0.9
        ipv6_address: 2fff:ffff::9
  google:
    cap_add:
    - CAP_NET_RAW
    - NET_ADMIN
    - SYS_ADMIN
    privileged: false
    container_name: google
    build:
      context: ./google
      dockerfile: Dockerfile
    volumes:
    - ./google/frr:/etc/frr:ro
    - ./google:/setup:ro
    sysctls:
    - net.ipv4.ip_forward=1
    - net.ipv6.conf.default.forwarding=1
    - net.ipv6.conf.all.forwarding=1
    - net.ipv6.conf.all.proxy_ndp=1
    - net.ipv6.conf.all.accept_ra=2
    command: "/bin/bash /setup/start.sh"
    networks:
      20-ldix:
        ipv4_address: 149.112.26.76
        ipv6_address: 2a0f:607:1070::76
      45-googledns:
        ipv4_address: 8.8.8.254
        ipv6_address: 2001:4860:4860::1
  googledns:
    cap_add:
    - CAP_NET_RAW
    - NET_ADMIN
    - SYS_ADMIN
    privileged: false
    container_name: googledns
    dns: 
    - 8.8.8.8
    - 2001:4860:4860::8888
    #- 198.41.0.4
    build:
      context: ./googledns
      dockerfile: Dockerfile
    volumes:
    - ./googledns:/setup:ro
    - ./googledns/bind/config:/etc/bind:rw
    - ./googledns/bind/zone:/var/cache/bind:rw
    command: "/bin/bash /setup/start.sh 8.8.8.254 2001:4860:4860::1"
    networks:
      45-googledns:
        ipv4_address: 8.8.8.8
        ipv6_address: 2001:4860:4860::8888
  othercloud:
    cap_add:
    - CAP_NET_RAW
    - NET_ADMIN
    - SYS_ADMIN
    privileged: false
    container_name: othercloud
    dns: 
    - 127.0.0.1
    build:
      context: ./othercloud
      dockerfile: Dockerfile
    volumes:
    - ./othercloud/frr:/etc/frr:ro
    - ./othercloud:/setup:ro
    - ./othercloud/nginx/sitesconf:/etc/nginx/sites-enabled:ro
    - ./othercloud/bind/apiconfig.yaml:/bindmanager/config.yaml:ro
    - ./othercloud/bind/config:/etc/bind:rw
    - ./othercloud/bind/zone:/var/cache/bind:rw
    - ./othercloud/nginx/certs:/etc/nginx/certs:rw
    sysctls:
    - net.ipv4.ip_forward=1
    - net.ipv6.conf.default.forwarding=1
    - net.ipv6.conf.all.forwarding=1
    - net.ipv6.conf.all.proxy_ndp=1
    - net.ipv6.conf.all.accept_ra=2
    command: "/bin/bash /setup/start.sh"
    networks:
      15-stutooc:
        ipv4_address: 10.187.0.2
        ipv6_address: 2fff:ffff::2
      25-ldtooc:
        ipv4_address: 10.187.0.10
        ipv6_address: 2fff:ffff::a
      30-cloudclt:
        ipv4_address: 187.187.187.254
        ipv6_address: 2def:abcd::1
  rootcaserver:
    cap_add:
    - CAP_NET_RAW
    - NET_ADMIN
    - SYS_ADMIN
    privileged: false
    container_name: rootcaserver
    build:
      context: https://github.com/NCKU-NASA/CA-server-api.git#master:.
      dockerfile: Dockerfile
    volumes:
    - ./rootcaserver/config.yaml:/usr/app/config.yaml:ro
    - ./rootcaserver/sign:/usr/app/sign:ro
    - ./rootcaserver/pki:/usr/app/mountpki:rw
    - ./rootcaserver:/setup:ro
    command: "/bin/bash /setup/start.sh 187.187.187.254 2def:abcd::1"
    networks:
      30-cloudclt:
        ipv4_address: 187.187.187.1
        ipv6_address: 2def:abcd::ca
  wscorg:
    cap_add:
    - CAP_NET_RAW
    - NET_ADMIN
    - SYS_ADMIN
    privileged: false
    container_name: wscorg
    build:
      context: ./wscorg
      dockerfile: Dockerfile
    volumes:
    - ./wscorg/frr:/etc/frr:ro
    - ./wscorg:/setup:ro
    sysctls:
    - net.ipv4.ip_forward=1
    - net.ipv6.conf.default.forwarding=1
    - net.ipv6.conf.all.forwarding=1
    - net.ipv6.conf.all.proxy_ndp=1
    - net.ipv6.conf.all.accept_ra=2
    command: "/bin/bash /setup/start.sh"
    networks:
      50-wscorg:
        ipv4_address: 103.69.91.234
        ipv6_address: 2407:9240:310f:ffff::ffea
      55-wscorgclt:
        ipv4_address: 139.39.39.254
        ipv6_address: 2390:3939:3939::1
